---
permalink: install/concept_dependency_between_zone_and_host_group_definitions.html 
sidebar: sidebar 
keywords: dependency, between, zone, host, group, definitions, common, errors, cascading, effect 
summary: 在區域定義中發生的錯誤可能需要重新設定主機群組定義和反向。 
---
= 區域與主機群組定義之間的相依性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在區域定義中發生的錯誤可能需要重新設定主機群組定義和反向。

建立區域定義時、會指定兩個連接埠： ONTAP 系統上 FC 啟動器連接埠的 WWPN 、以及該區域的儲存陣列連接埠 WWPN 或 WWNN 。同樣地、在儲存陣列上設定 ONTAP 系統的主機群組時、會指定您要成為主機群組成員的 FC 啟動器連接埠的 WWPN 。

組態的一般順序如下：

. 建構區域定義。
. 在儲存陣列上建構主機群組（從選單中選取 ONTAP 系統上 FC 啟動器連接埠的 WWPN ）。
. 向連接埠呈現陣列 LUN 。


不過、主機群組有時會在區域定義之前進行設定、這需要在儲存陣列的主機群組組組態中手動輸入 WWPN 。



== 常見錯誤

在 ONTAP 輸出中、 ONTAP 系統上的 FC 啟動器連接埠會以介面卡編號來識別、例如 0A 、 0b 、 0c 、 0d 、 此外、也適用於內建連接埠的機型。WWPN 顯示在交換器 GUI 和儲存陣列 GUI 中。由於 WWPN 是長的十六進位格式、因此常見的錯誤如下：

[cols="2*"]
|===
| 如何指定 WWPN | 一般錯誤 


 a| 
系統管理員輸入 WWPN
 a| 
輸入錯誤。



 a| 
交換器會自動探索 WWPN
 a| 
從選擇清單中選取錯誤的 FC 啟動器連接埠 WWPN 。

|===
[NOTE]
====
當 ONTAP 系統、交換器和儲存陣列連接在一起時、交換器會自動探索 ONTAP 系統和儲存陣列連接埠的 WWPN 。然後、交換器 GUI 的選單中會提供 WWPN 、讓您可以選擇每個區域成員的 WWPN 、而非輸入。為了消除輸入錯誤的可能性、建議交換器探索 WWPN 。

====


== 錯誤的串聯影響

疑難排解光纖附加組態問題時、最明顯的第一步是檢查分區設定是否正確。考慮到主機群組與區域定義之間的關係也很重要。修復問題可能需要重新設定區域定義和主機群組定義、視設定程序期間發生錯誤的位置而定。

如果交換器會自動探索 WWPN 、且首先設定區域定義、則用於存取儲存陣列上 LUN 的 FC 啟動器連接埠的 WWPN 會自動傳播至儲存陣列 GUI 中的主機群組組組態選項清單。因此、任何分區錯誤也會傳播至儲存陣列主機群組選擇清單。挑選清單會顯示長型十六進位 WWPN 、而非 ONTAP 系統上可見的短 FC 啟動器連接埠標籤（例如 0A 、 0b 等）。因此、不容易看出您預期要列出的 WWPN 不在這裡。

下表顯示某些錯誤的影響：

[cols="3*"]
|===
| 交換器上的區域定義 | 儲存陣列上的主機群組組組態 | ONTAP 輸出中的症狀 


 a| 
區域定義中的 FC 啟動器連接埠不正確。這會導致不正確的 FC 啟動器連接埠 WWPN 傳播至主機群組組組態。
 a| 
選取清單中顯示的 FC 啟動器連接埠 WWPN 已選取、而非您想要的 WWPN 。
 a| 
陣列 LUN 無法透過 FC 啟動器連接埠看見、而預期的 LUN 會顯示在該連接埠上。



 a| 
區域定義包括正確的 FC 啟動器連接埠。
 a| 
主機群組定義中的 WWPN 不正確、原因如下：

* 選擇了錯誤的 WWPN 。
* 在設定區域定義之前手動設定主機群組、並在輸入 FC 啟動器連接埠的 WWPN 時發生輸入錯誤。

 a| 

|===